### PR TITLE
Fix handling of `include/secutils/static_config.h` with `Makefile_v1`

### PR DESCRIPTION
**Pull request by DDvO**
As mentioned in https://github.com/siemens/libsecutils/pull/43#discussion_r1206283876,
there is need to improve the handling of the config file, also for backward compatibility in `Makefile_v1`.
Done here.

### CODE REVIEW

**Comment by xsulca00** [comment]
Thank you for altering Makefile_v1 so it can be compatible with CMake changes. I have tried to compile it locally on my machine using command `make -f Makefile_v1` and sometimes it did not compile. I think Make needs a better dependency ordering otherwise it runs those targets independently. When I put the generated `static_config.h` as a dependency for `$(OBJS)` seems like it did the job. What do you think?
image

**Comment by DDvO** [comment]
> I have tried to compile it locally on my machine using command `make -f Makefile_v1` and sometimes it did not compile. I think Make needs a better dependency ordering otherwise it runs those targets independently. 
> When I put the generated `static_config.h` as a dependency for `$(OBJS)` seems like it does the job. What do you think?

Thank you for trying and the improvement you suggested.
I think moving the dependency to the end of the line
```
$(BUILDDIR)/%$(OBJ): %.c
```
will be even better.

**Comment by DDvO** [comment]
I also renamed `static_config.h` to `secutils_static_config.h` to prevent potential name clashes with other libraries.

**Comment by DDvO** [comment]
@benjamin-schilling can you approve this soon?

**Comment by xsulca00** [comment]
I am afraid that Doxygen needs a dependency too because it uses the `static_config.h` header file to generate documentation too. It has crashed a few times during Make run because of that (ignore CMake changes):
image

**Comment by DDvO** [comment]
Hmm, I cannot reproduce a Doxygen crash on my copy of this branch.
```
 make -f Makefile_v1 clean doc
```
works just fine.
Why do you think the explicit reference to `secutils_static_config.h` is needed?

Of course, in your PR #43 where you moved the include directories, you need to adapt `Makefile_v1` accordingly.

**Comment by DDvO** [comment]
> Of course, in your PR #43 where you moved the include directories, you need to adapt `Makefile_v1` accordingly.

Since your above diff already includes this adaptation, where the wildcard *.h covers the new `secutils_static_config.h` file, I propose just dropping the latter from the list.

**Comment by DDvO** [comment]
Just found a further fixup was needed on this PR, for `make -f Makefile_v1 deb`.

**Comment by xsulca00** [comment]
Nice, I will just leave it now and I will fix it later in my CMake branch. Hopefully it is just my mistake after changing of all the paths to includes.

**Comment by xsulca00** [comment]
An interesting observation. If I change this to a concrete path, then it works:
image

Otherwise for some reason it deletes the `secutils_static_config.h` file:
image

**Comment by DDvO** [comment]
> Just found a further fixup was needed on this PR, for `make -f Makefile_v1 deb`.

Yet another fixup on this, sigh.
'Manual' Debian packaging is a PITA.

**Comment by DDvO** [comment]
> An interesting observation. If I change this to a concrete path, then it works: image
> 
> Otherwise for some reason it deletes the `secutils_static_config.h` file:

Really interesting.
I have no idea why.

**Comment by DDvO** [comment]
To be on the safe side, I've replaced the generic target
```
%.h: %.h.in
```
by
```
SECUTILS_CONFIG=include/secutils/secutils_static_config.h
$(SECUTILS_CONFIG): $(SECUTILS_CONFIG).in
```

**Comment by DDvO** [comment]
@benjamin-schilling, I will be on vacation next week.

Would be nice if we can merge this PR today.

**Review by benjamin-schilling — APPROVED** [review]

**Pull request merged**
