### PR TITLE
clean up and move cert-related functions to new `cert.{c,h}`

### PR DESCRIPTION
**Pull request by DDvO**
Also generalize `UTIL_warn_cert{,s}` to `CERT_check{,_all}`

### CODE REVIEW

**Comment by DDvO** [comment]
Benjamin, this PR looks bulky, but most of it just just shuffling code and header items to the new files where they fit much better.

**Comment by DDvO** [comment]
Whenever changing function names, e.g., `UTIL_print_cert()` to `CERT_print()`,
I added a `#define` for API backward compatibility.

**Comment by DDvO** [comment]
@benjamin-schilling would it help reviewing if I split this PR into one renaming and adapting functions and one with the rest, i.e., moving contents from various places to `cert.{c,h}`?

**Review by benjamin-schilling — APPROVED** [review]

**Comment by DDvO** [comment]
Merged to master, squashing fixups - 
thanks @benjamin-schilling for the approval.

**Pull request closed without merging**
